-- MySQL Script generated by MySQL Workbench
-- Thu May 25 17:50:00 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FinalProject
-- -----------------------------------------------------
--  

-- -----------------------------------------------------
-- Schema FinalProject
--
--  
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FinalProject`;
USE `FinalProject` ;

-- -----------------------------------------------------
-- Table `FinalProject`.`DevelopmentCompany`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinalProject`.`DevelopmentCompany` (
  `DevelopmentCompanyID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(200) NULL,
  PRIMARY KEY (`DevelopmentCompanyID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinalProject`.`AppVersion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinalProject`.`AppVersion` (
  `AppVersionID` INT NOT NULL AUTO_INCREMENT,
  `VersionNumber` DECIMAL(3,1) NOT NULL,
  `ReleaseDate` DATE NOT NULL,
  PRIMARY KEY (`AppVersionID`)
) ENGINE=InnoDB;


-- -----------------------------------------------------
-- Table `FinalProject`.`App`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinalProject`.`App` (
  `AppID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(255) NULL,
  `AppVersionID` INT NOT NULL,
  `DevelopmentCompanyID` INT NOT NULL,
  PRIMARY KEY (`AppID`, `AppVersionID`, `DevelopmentCompanyID`),
  INDEX `fk_App_AppVersion1_idx` (`AppVersionID` ASC) VISIBLE,
  INDEX `fk_App_DevelopmentCompany1_idx` (`DevelopmentCompanyID` ASC) VISIBLE,
  CONSTRAINT `fk_App_AppVersion1`
    FOREIGN KEY (`AppVersionID`)
    REFERENCES `FinalProject`.`AppVersion` (`AppVersionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_App_DevelopmentCompany1`
    FOREIGN KEY (`DevelopmentCompanyID`)
    REFERENCES `FinalProject`.`DevelopmentCompany` (`DevelopmentCompanyID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinalProject`.`MonthAmount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinalProject`.`MonthAmount` (
	`MonthAmountID` INT NOT NULL AUTO_INCREMENT,
	`January` FLOAT NULL,
	`February` FLOAT NULL,
	`March` FLOAT NULL,
	`April` FLOAT NULL,
	`May` FLOAT NULL,
	`June` FLOAT NULL,
	`July` FLOAT NULL,
	`August` FLOAT NULL,
	`September` FLOAT NULL,
	`October` FLOAT NULL,
	`November` FLOAT NULL,
	`December` FLOAT NULL,
  PRIMARY KEY (`MonthAmountID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinalProject`.`DataCenter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinalProject`.`DataCenter` (
  `DataCenterID` INT NOT NULL AUTO_INCREMENT,
  `Location` VARCHAR(45) NOT NULL,
  `CurrentLoad` FLOAT NOT NULL,
  `ReservedResources` FLOAT NOT NULL,
  `FreeResources` FLOAT NOT NULL,
  `MonthAmountID` INT NOT NULL,
  `Latitude` FLOAT NOT NULL,
  `Longitude` FLOAT NOT NULL,
  PRIMARY KEY (`DataCenterID`),
  INDEX `fk_DataCenter_MonthAmount1_idx` (`MonthAmountID` ASC) VISIBLE,
  CONSTRAINT `fk_DataCenter_MonthAmount1`
    FOREIGN KEY (`MonthAmountID`)
    REFERENCES `FinalProject`.`MonthAmount` (`MonthAmountID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinalProject`.`OperatingSystem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinalProject`.`OperatingSystem` (
  `OperatingSystemID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`OperatingSystemID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinalProject`.`VMState`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinalProject`.`VMState` (
  `VMStateID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`VMStateID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinalProject`.`Software`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinalProject`.`Software` (
  `SoftwareID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`SoftwareID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinalProject`.`VirtualMachine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinalProject`.`VirtualMachine` (
  `VirtualMachineID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Description` VARCHAR(200) NULL,
  `CPU` INT NULL,
  `RAM` INT NULL,
  `Storage` INT NULL,
  `OperatingSystemID` INT NOT NULL,
  `VMStateID` INT NOT NULL,
  `DataCenterID` INT NOT NULL,
  `SoftwareID` INT NOT NULL,
  PRIMARY KEY (`VirtualMachineID`),
  INDEX `fk_VirtualMachine_OperatingSystem1_idx` (`OperatingSystemID` ASC) VISIBLE,
  INDEX `fk_VirtualMachine_VMState1_idx` (`VMStateID` ASC) VISIBLE,
  INDEX `fk_VirtualMachine_DataCenter1_idx` (`DataCenterID` ASC) VISIBLE,
  INDEX `fk_VirtualMachine_Software1_idx` (`SoftwareID` ASC) VISIBLE,
  CONSTRAINT `fk_VirtualMachine_OperatingSystem1`
    FOREIGN KEY (`OperatingSystemID`)
    REFERENCES `FinalProject`.`OperatingSystem` (`OperatingSystemID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_VirtualMachine_VMState1`
    FOREIGN KEY (`VMStateID`)
    REFERENCES `FinalProject`.`VMState` (`VMStateID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_VirtualMachine_DataCenter1`
    FOREIGN KEY (`DataCenterID`)
    REFERENCES `FinalProject`.`DataCenter` (`DataCenterID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_VirtualMachine_Software1`
    FOREIGN KEY (`SoftwareID`)
    REFERENCES `FinalProject`.`Software` (`SoftwareID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinalProject`.`BalancePolicy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinalProject`.`BalancePolicy` (
  `BalancePolicyID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`BalancePolicyID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinalProject`.`RequestRate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinalProject`.`RequestRate` (
  `RequestRateID` INT NOT NULL AUTO_INCREMENT,
	`RequestsPerSecond` INT NOT NULL,
	`RequestsPerMinute` INT NOT NULL,
	`RequestsPerHour` INT NOT NULL,
  PRIMARY KEY (`RequestRateID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinalProject`.`LoadBalancer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinalProject`.`LoadBalancer` (
  `LoadBalancerID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(200) NULL,
  `IPdns` VARCHAR(45) NOT NULL,
  `BalancePolicyID` INT NOT NULL,
  `RequestRateID` INT NOT NULL,
  `DataCenterID` INT NOT NULL,
  PRIMARY KEY (`LoadBalancerID`),
  INDEX `fk_BalancePolicy_LoadBalancer1_idx` (`BalancePolicyID` ASC) VISIBLE,
  INDEX `fk_LoadBalancer_RequestRate1_idx` (`RequestRateID` ASC) VISIBLE,
  INDEX `fk_LoadBalancer_DataCenter1_idx` (`DataCenterID` ASC) VISIBLE,
  CONSTRAINT `fk_BalancePolicy_LoadBalancer1`
    FOREIGN KEY (`BalancePolicyID`)
    REFERENCES `FinalProject`.`BalancePolicy` (`BalancePolicyID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_LoadBalancer_RequestRate1`
    FOREIGN KEY (`RequestRateID`)
    REFERENCES `FinalProject`.`RequestRate` (`RequestRateID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_LoadBalancer_DataCenter1`
    FOREIGN KEY (`DataCenterID`)
    REFERENCES `FinalProject`.`DataCenter` (`DataCenterID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinalProject`.`Authentication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinalProject`.`Authentication` (
  `AuthenticationID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`AuthenticationID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinalProject`.`TimeSlot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinalProject`.`TimeSlot` (
  `TimeSlotID` INT NOT NULL AUTO_INCREMENT,
  `StartTime` DATETIME NULL,
  `EndTime` DATETIME NULL,
  PRIMARY KEY (`TimeSlotID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinalProject`.`RequestState`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinalProject`.`RequestState` (
  `RequestStateID` INT NOT NULL AUTO_INCREMENT,
  `State` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`RequestStateID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinalProject`.`RequestLog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinalProject`.`RequestLog` (
  `RequestLogID` INT NOT NULL AUTO_INCREMENT,
  `Quantity` INT NULL,
  `TimeSlotID` INT NOT NULL,
  `RequestStateID` INT NOT NULL,
  PRIMARY KEY (`RequestLogID`),
  INDEX `fk_RequestLog_TimeSlot1_idx` (`TimeSlotID` ASC) VISIBLE,
  INDEX `fk_RequestLog_RequestState1_idx` (`RequestStateID` ASC) VISIBLE,
  CONSTRAINT `fk_RequestLog_TimeSlot1`
    FOREIGN KEY (`TimeSlotID`)
    REFERENCES `FinalProject`.`TimeSlot` (`TimeSlotID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_RequestLog_RequestState1`
    FOREIGN KEY (`RequestStateID`)
    REFERENCES `FinalProject`.`RequestState` (`RequestStateID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinalProject`.`DailyLog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinalProject`.`DailyLog` (
  `DailyLogID` INT NOT NULL AUTO_INCREMENT,
  `Morning` INT NOT NULL,
  `Afternoon` INT NOT NULL,
  `Evening` INT NULL,
  PRIMARY KEY (`DailyLogID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinalProject`.`LoginStats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinalProject`.`LoginStats` (
  `LoginStatsID` INT NOT NULL AUTO_INCREMENT,
  `LogDate` DATE NOT NULL,
  `TimeSlot` VARCHAR(45) NOT NULL,
  `Counts` INT NOT NULL,
  `DailyLogID` INT NOT NULL,
  PRIMARY KEY (`LoginStatsID`),
  INDEX `fk_LoginStats_DailyLog1_idx` (`DailyLogID` ASC) VISIBLE,
  CONSTRAINT `fk_LoginStats_DailyLog1`
    FOREIGN KEY (`DailyLogID`)
    REFERENCES `FinalProject`.`DailyLog` (`DailyLogID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinalProject`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinalProject`.`Login` (
  `LoginID` INT NOT NULL AUTO_INCREMENT,
  `ServerID` INT NOT NULL,
  `AuthenticationID` INT NOT NULL,
  `RequestLogID` INT NOT NULL,
  `LoginStatsID` INT NOT NULL,
  PRIMARY KEY (`LoginID`),
  INDEX `fk_Login_Authentication1_idx` (`AuthenticationID` ASC) VISIBLE,
  INDEX `fk_Login_Request1_idx` (`RequestLogID` ASC) VISIBLE,
  INDEX `fk_Login_LoginStats1_idx` (`LoginStatsID` ASC) VISIBLE,
  CONSTRAINT `fk_Login_Authentication1`
    FOREIGN KEY (`AuthenticationID`)
    REFERENCES `FinalProject`.`Authentication` (`AuthenticationID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Login_RequestLog1`
    FOREIGN KEY (`RequestLogID`)
    REFERENCES `FinalProject`.`RequestLog` (`RequestLogID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Login_LoginStats1`
    FOREIGN KEY (`LoginStatsID`)
    REFERENCES `FinalProject`.`LoginStats` (`LoginStatsID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinalProject`.`Server`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinalProject`.`Server` (
  `ServerID` INT NOT NULL AUTO_INCREMENT,
  `InternalName` VARCHAR(45) NOT NULL,
  `ExternalName` VARCHAR(45) NOT NULL,
  `AssignedSpace` INT NOT NULL,
  `AvailableSpace` INT NOT NULL,
  `DataCenterID` INT NOT NULL,
  `LoginID` INT NOT NULL,
  PRIMARY KEY (`ServerID`),
  INDEX `fk_Server_DataCenter1_idx` (`DataCenterID` ASC) VISIBLE,
  INDEX `fk_Server_Login1_idx` (`LoginID` ASC) VISIBLE,
  CONSTRAINT `fk_Server_DataCenter1`
    FOREIGN KEY (`DataCenterID`)
    REFERENCES `FinalProject`.`DataCenter` (`DataCenterID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Server_Login1`
    FOREIGN KEY (`LoginID`)
    REFERENCES `FinalProject`.`Login` (`LoginID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinalProject`.`DataCenterEvent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinalProject`.`DataCenterEvent` (
  `DataCenterEventID` INT NOT NULL AUTO_INCREMENT,
  `DataCenterID` INT NOT NULL,
  `EventDate` DATE NULL,
  `EventTime` TIME NULL,
  `Consumption` DECIMAL NULL,
  PRIMARY KEY (`DataCenterEventID`),
  INDEX `fk_DataCenterEvent_DataCenter1_idx` (`DataCenterID` ASC) VISIBLE,
  CONSTRAINT `fk_DataCenterEvent_DataCenter1`
    FOREIGN KEY (`DataCenterID`)
    REFERENCES `FinalProject`.`DataCenter` (`DataCenterID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinalProject`.`AppStats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinalProject`.`AppStats` (
  `AppStatsID` INT NOT NULL AUTO_INCREMENT,
  `AppID` INT NOT NULL,
  `StartDate` DATE NULL,
  `EndDate` DATE NULL,
  `Frequency` VARCHAR(45) NULL,
  `MetricType` VARCHAR(45) NULL,
	`Value` DECIMAL NULL,
  PRIMARY KEY (`AppStatsID`),
  INDEX `fk_AppStats_App1_idx` (`AppID` ASC) VISIBLE,
  CONSTRAINT `fk_AppStats_App1`
    FOREIGN KEY (`AppID`)
    REFERENCES `FinalProject`.`App` (`AppID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinalProject`.`CumulativeConsumption`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinalProject`.`CumulativeConsumption` (
  `CumulativeConsumptionID` INT NOT NULL AUTO_INCREMENT,
  `DataCenterID` INT NOT NULL,
  `EventDate` DATE NULL,
  `EventTime` TIME NULL,
  `AccumulatedConsumption` DECIMAL NULL,
  PRIMARY KEY (`CumulativeConsumptionID`),
  INDEX `fk_CumulativeConsumption_DataCenter1_idx` (`DataCenterID` ASC) VISIBLE,
  CONSTRAINT `fk_CumulativeConsumption_DataCenter1`
    FOREIGN KEY (`DataCenterID`)
    REFERENCES `FinalProject`.`DataCenter` (`DataCenterID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
